export { default as Page404 } from "./404/404";
export { default as Admin } from "./admin/Admin";
export { default as Create } from "./admin/Create";
export { default as Edit } from "./admin/Edit";
export { default as Users } from "./admin/Users";
export { default as Post } from "./post/Post";
export { default as Search } from "./search/Search";
export { default as Home } from "./home/Home";
export { default as Trailers } from "./trailers/Trailers";
